# Generated by Django 3.0.5 on 2020-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('username', models.TextField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('tweet', models.TextField(max_length=280)),
                ('geo', models.CharField(max_length=25)),
                ('positive', models.BooleanField(default=False)),
                ('happy', models.BooleanField(default=False)),
                ('relief', models.BooleanField(default=False)),
                ('neutral', models.BooleanField(default=False)),
                ('anxious', models.BooleanField(default=False)),
                ('sad', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
            ],
        ),
    ]
