# Generated by Django 3.0.7 on 2020-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='batch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
