# Generated by Django 3.0.7 on 2020-07-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tweets_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='anxious',
            new_name='Anxious',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='happy',
            new_name='Happy',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='negative',
            new_name='Negative',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='neutral',
            new_name='Neutral',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='positive',
            new_name='Positive',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='relief',
            new_name='Relief',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='sad',
            new_name='Sad',
        ),
    ]
